In [3]:
import sys
sys.path.append("..")

In [4]:
import joblib
from pathlib import Path
import numpy as np
import pandas as pd

from src.tokenizer.corpus import Corpus
from src.tokenizer.statistics import Statistics
from src.tokenizer.candidates import CandidateExtractor
from src.tokenizer.vocabulary import VocabularyBuilder
from src.tokenizer.normalizer import Normalizer
from src.tokenizer.vectorizer import VocabularyVectorizer

In [5]:
df = pd.read_csv(
    "../data/text_corpus.csv",
    encoding="utf-8"
)


texts = df["comment"].tolist()


corpus = Corpus(texts)

In [6]:
print(type(corpus))

print(len(corpus))

<class 'src.tokenizer.corpus.Corpus'>
10000

In [7]:
stats = Statistics().fit(corpus)

In [8]:
len(stats.phrase_freq)

1559

In [9]:

normalizer = Normalizer()

extractor = CandidateExtractor(
    normalizer=normalizer,
    min_freq=20
)

candidates = extractor.extract(stats)

builder = VocabularyBuilder()

vocabulary = builder.build(candidates)

In [10]:
len(candidates), len(vocabulary)

(506, 506)

In [11]:

df_vocab = builder.to_dataframe(vocabulary)

df_vocab.head(50)

,text,freq,score,parent_count,child_count,redundancy,rank
0,неисправность оборудования,5343,15112.286128,1,2,1.092638,13298.811792
1,есть проблемы,3586,10142.739669,0,0,0.000000,10142.739669
2,оборудования провайдера,2894,8185.468099,0,3,0.000000,9413.288314
3,проблема оборудования,2621,7413.307494,1,1,0.555297,7783.972869
4,неисправность оборудования провайдера,1479,7685.109433,2,0,0.302454,7685.109433
5,проблема абонентского,2536,7172.891188,1,1,0.537288,7531.535748
6,отсутствует,6159,6159.000000,0,4,0.000000,7390.800000
7,неисправность оборудования абонента,1419,7373.340288,2,0,0.290184,7373.340288
8,проблема оборудования провайдера,1415,7352.555678,2,0,0.539870,7352.555678
9,проблема абонентского оборудования,1382,7181.082648,2,0,0.544953,7181.082648
10,в интернет,1388,3925.856849,0,16,0.000000,7066.542328
11,неверная конфигурация по,1187,6167.832926,2,0,0.581863,6167.832926
12,плохое качество,2136,6041.520338,0,0,0.000000,6041.520338
13,проблема,4720,4720.000000,0,4,0.000000,5664.000000
14,неисправность,4890,4890.000000,0,3,0.000000,5623.500000
15,доступ в интернет,1350,7014.805771,2,0,4.804270,5611.844617
16,неверная конфигурация,2207,6242.338664,1,1,1.081863,5243.564478
17,работают приложения,1544,4367.091481,0,0,0.000000,4367.091481
18,оборудования абонента,1419,4013.538090,0,1,0.000000,4214.214995
19,авария,3300,3300.000000,0,5,0.000000,4125.000000
20,абонентского оборудования,1382,3908.886286,0,1,0.000000,4104.330601
21,проблемы,3484,3484.000000,0,3,0.000000,4006.600000
22,соединение отсутствует,1308,3699.582679,0,0,0.000000,3699.582679
23,конфигурация по,1187,3357.342997,0,2,0.000000,3693.077297
24,авария на,1203,3402.597831,1,1,0.364545,3572.727723
25,авария сети,1188,3360.171424,1,1,0.360000,3528.179995
26,не работают приложения,848,4406.337254,1,0,1.000000,3525.069804
27,авария оборудования,1220,3450.681092,1,0,0.369697,3450.681092
28,нет соединения,1212,3428.053675,0,0,0.000000,3428.053675
29,авария на стороне,658,3419.068294,2,0,0.546966,3419.068294
30,доступ в,1350,3818.376618,1,1,4.804270,3207.436359
31,стороне провайдера,1316,3722.210096,1,0,2.000000,2977.768077
32,падает сессия,1017,2876.510386,0,0,0.000000,2876.510386
33,интернет отсутствует,1202,3399.769404,1,0,2.756881,2719.815523
34,не работают,848,2398.506202,0,1,0.000000,2518.431512
35,качество,2068,2068.000000,0,2,0.000000,2274.800000
36,неверная,2040,2040.000000,0,2,0.000000,2244.000000
37,воздействие третьей стороны,406,2109.637884,2,0,0.593567,2109.637884
38,интернет есть проблемы,459,2385.033962,2,0,1.052752,1908.027170
39,воздействие третьей,748,2115.663489,1,1,1.093567,1777.157331
40,в интернет отсутствует,314,1631.591861,1,0,0.226225,1631.591861
41,шпд отсутствует,690,1951.614716,1,0,2.017544,1561.291773
42,цифровое тв,494,1397.243000,1,7,4.116667,1509.022440
43,приложения,1337,1337.000000,0,0,0.000000,1337.000000
44,интернет,436,436.000000,0,37,0.000000,1242.600000
45,интернет плохое качество,283,1470.511136,2,0,1.000000,1176.408909
46,услуге доступ в,281,1460.118831,1,0,1.000000,1168.095065
47,в интернет есть,224,1163.938143,1,0,0.161383,1163.938143
48,третьей стороны,406,1148.341413,0,0,0.000000,1148.341413
49,интернет есть,459,1298.248050,1,1,1.052752,1090.528362

In [12]:
df_vocab.sort_values(
    "rank",
    ascending=False
).head(50)

,text,freq,score,parent_count,child_count,redundancy,rank
0,неисправность оборудования,5343,15112.286128,1,2,1.092638,13298.811792
1,есть проблемы,3586,10142.739669,0,0,0.000000,10142.739669
2,оборудования провайдера,2894,8185.468099,0,3,0.000000,9413.288314
3,проблема оборудования,2621,7413.307494,1,1,0.555297,7783.972869
4,неисправность оборудования провайдера,1479,7685.109433,2,0,0.302454,7685.109433
5,проблема абонентского,2536,7172.891188,1,1,0.537288,7531.535748
6,отсутствует,6159,6159.000000,0,4,0.000000,7390.800000
7,неисправность оборудования абонента,1419,7373.340288,2,0,0.290184,7373.340288
8,проблема оборудования провайдера,1415,7352.555678,2,0,0.539870,7352.555678
9,проблема абонентского оборудования,1382,7181.082648,2,0,0.544953,7181.082648
10,в интернет,1388,3925.856849,0,16,0.000000,7066.542328
11,неверная конфигурация по,1187,6167.832926,2,0,0.581863,6167.832926
12,плохое качество,2136,6041.520338,0,0,0.000000,6041.520338
13,проблема,4720,4720.000000,0,4,0.000000,5664.000000
14,неисправность,4890,4890.000000,0,3,0.000000,5623.500000
15,доступ в интернет,1350,7014.805771,2,0,4.804270,5611.844617
16,неверная конфигурация,2207,6242.338664,1,1,1.081863,5243.564478
17,работают приложения,1544,4367.091481,0,0,0.000000,4367.091481
18,оборудования абонента,1419,4013.538090,0,1,0.000000,4214.214995
19,авария,3300,3300.000000,0,5,0.000000,4125.000000
20,абонентского оборудования,1382,3908.886286,0,1,0.000000,4104.330601
21,проблемы,3484,3484.000000,0,3,0.000000,4006.600000
22,соединение отсутствует,1308,3699.582679,0,0,0.000000,3699.582679
23,конфигурация по,1187,3357.342997,0,2,0.000000,3693.077297
24,авария на,1203,3402.597831,1,1,0.364545,3572.727723
25,авария сети,1188,3360.171424,1,1,0.360000,3528.179995
26,не работают приложения,848,4406.337254,1,0,1.000000,3525.069804
27,авария оборудования,1220,3450.681092,1,0,0.369697,3450.681092
28,нет соединения,1212,3428.053675,0,0,0.000000,3428.053675
29,авария на стороне,658,3419.068294,2,0,0.546966,3419.068294
30,доступ в,1350,3818.376618,1,1,4.804270,3207.436359
31,стороне провайдера,1316,3722.210096,1,0,2.000000,2977.768077
32,падает сессия,1017,2876.510386,0,0,0.000000,2876.510386
33,интернет отсутствует,1202,3399.769404,1,0,2.756881,2719.815523
34,не работают,848,2398.506202,0,1,0.000000,2518.431512
35,качество,2068,2068.000000,0,2,0.000000,2274.800000
36,неверная,2040,2040.000000,0,2,0.000000,2244.000000
37,воздействие третьей стороны,406,2109.637884,2,0,0.593567,2109.637884
38,интернет есть проблемы,459,2385.033962,2,0,1.052752,1908.027170
39,воздействие третьей,748,2115.663489,1,1,1.093567,1777.157331
40,в интернет отсутствует,314,1631.591861,1,0,0.226225,1631.591861
41,шпд отсутствует,690,1951.614716,1,0,2.017544,1561.291773
42,цифровое тв,494,1397.243000,1,7,4.116667,1509.022440
43,приложения,1337,1337.000000,0,0,0.000000,1337.000000
44,интернет,436,436.000000,0,37,0.000000,1242.600000
45,интернет плохое качество,283,1470.511136,2,0,1.000000,1176.408909
46,услуге доступ в,281,1460.118831,1,0,1.000000,1168.095065
47,в интернет есть,224,1163.938143,1,0,0.161383,1163.938143
48,третьей стороны,406,1148.341413,0,0,0.000000,1148.341413
49,интернет есть,459,1298.248050,1,1,1.052752,1090.528362

In [13]:
df_vocab[
    df_vocab["text"].str.contains(
        "авария|неисправность|оборудование|соединение"
    )
].head(50)

,text,freq,score,parent_count,child_count,redundancy,rank
0,неисправность оборудования,5343,15112.286128,1,2,1.092638,13298.811792
4,неисправность оборудования провайдера,1479,7685.109433,2,0,0.302454,7685.109433
7,неисправность оборудования абонента,1419,7373.340288,2,0,0.290184,7373.340288
14,неисправность,4890,4890.000000,0,3,0.000000,5623.500000
19,авария,3300,3300.000000,0,5,0.000000,4125.000000
22,соединение отсутствует,1308,3699.582679,0,0,0.000000,3699.582679
24,авария на,1203,3402.597831,1,1,0.364545,3572.727723
25,авария сети,1188,3360.171424,1,1,0.360000,3528.179995
27,авария оборудования,1220,3450.681092,1,0,0.369697,3450.681092
29,авария на стороне,658,3419.068294,2,0,0.546966,3419.068294
68,зарегистрировано соединение отсутствует,195,1013.249722,1,0,1.000000,810.599778
74,причина неисправность оборудования,173,898.934369,1,0,1.000000,719.147495
90,зарегистрировано соединение,195,551.543289,0,1,0.000000,579.120454
102,причина неисправность,173,489.317893,0,1,0.000000,513.783787
123,отсутствует причина неисправность,79,410.496041,1,0,0.012827,410.496041
143,причина авария,104,294.156421,0,3,0.000000,338.279884
149,интернет соединение отсутствует,76,394.907584,2,0,1.000000,315.926067
172,шпд соединение отсутствует,65,337.749907,2,0,1.000000,270.199926
179,отсутствует причина авария,50,259.807621,1,0,0.008118,259.807621
203,интернет соединение,76,214.960461,1,1,0.174312,225.708485
210,в интернет соединение,42,218.238402,1,0,0.030259,218.238402
220,причина авария на,39,202.649944,1,0,0.375000,202.649944
228,шпд соединение,65,183.847763,1,1,0.190058,193.040151
249,fttx неисправность оборудования,43,223.434554,2,0,1.000000,178.747643
264,причина авария оборудования,33,171.473030,1,0,0.317308,171.473030
271,причина авария сети,32,166.276878,1,0,0.307692,166.276878
272,проблемы причина неисправность,32,166.276878,1,0,0.009185,166.276878
294,gpon авария на,37,192.257640,2,0,1.000000,153.806112
310,pon авария оборудования,35,181.865335,2,0,1.000000,145.492268
319,пара зарегистрировано соединение,27,140.296115,1,0,0.600000,140.296115
332,аналоговая телефония соединение,26,135.099963,2,0,0.329114,135.099963
339,интернет fttx неисправность,25,129.903811,2,0,0.163399,129.903811
344,fttx неисправность,43,121.622366,1,1,0.330769,127.703485
353,fttx зарегистрировано соединение,24,124.707658,2,0,0.184615,124.707658
356,витая пара неисправность,24,124.707658,2,0,0.533333,124.707658
357,legacy зарегистрировано соединение,24,124.707658,2,0,0.500000,124.707658
363,xpon авария сети,29,150.688420,2,0,1.000000,120.550736
365,gpon неисправность оборудования,29,150.688420,2,0,1.000000,120.550736
366,авария сети выполняется,23,119.511506,2,0,0.019360,119.511506
377,iot соединение отсутствует,28,145.492268,2,0,1.000000,116.393814
394,fttx авария,39,110.308658,1,0,0.300000,110.308658
396,gpon авария,37,104.651804,1,1,0.324561,109.884394
398,качество причина неисправность,21,109.119201,1,0,0.010155,109.119201
399,беспроводной шпд неисправность,21,109.119201,2,0,0.388889,109.119201
400,проблемы причина авария,21,109.119201,1,0,0.006028,109.119201
404,телефония соединение отсутствует,26,135.099963,1,0,1.000000,108.079970
412,pon авария,35,98.994949,1,1,0.327103,103.944697
415,tdm зарегистрировано соединение,20,103.923048,2,0,0.465116,103.923048
420,цифровое тв соединение,20,103.923048,2,0,0.166667,103.923048
423,пара неисправность оборудования,24,124.707658,1,0,1.000000,99.766127

In [14]:
df_vocab.sort_values("rank", ascending=False).reset_index(drop=True).reset_index(
    ).rename(columns={'index':'token_id'}).to_csv("../data/vocabulary.csv", index=False)

df_vocab = pd.read_csv("../data/vocabulary.csv")
df_vocab.info()

<class 'pandas.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   token_id      506 non-null    int64
 1   text          506 non-null    str
 2   freq          506 non-null    int64
 3   score         506 non-null    float64
 4   parent_count  506 non-null    int64
 5   child_count   506 non-null    int64
 6   redundancy    506 non-null    float64
 7   rank          506 non-null    float64
dtypes: float64(3), int64(4), str(1)
memory usage: 31.8 KB

In [15]:
len(df_vocab)

506

In [16]:
df_vocab["freq"].describe()

count     506.000000
mean      236.124506
std       642.334334
min        20.000000
25%        30.000000
50%        49.000000
75%       120.750000
max      6159.000000
Name: freq, dtype: float64

In [17]:
vocab_set = set(
    df_vocab["text"]
)

coverage = []

for text in corpus:

    count = 0

    for token in vocab_set:

        if token in text.lower():
            count += 1

    coverage.append(count)

pd.Series(coverage).describe()

count    10000.000000
mean         8.601200
std          2.403734
min          3.000000
25%          7.000000
50%          8.000000
75%         10.000000
max         17.000000
dtype: float64

In [18]:
df_vocab.sort_values(
    "freq"
).head(50)

,token_id,text,freq,score,parent_count,child_count,redundancy,rank
454,454,абонента передано специалистам,20,103.923048,1,0,1.000000,83.138439
455,455,wi-fi проблема абонентского,20,103.923048,2,0,1.000000,83.138439
457,457,pon соединение отсутствует,20,103.923048,2,0,1.000000,83.138439
460,460,wi-fi есть проблемы,20,103.923048,2,0,1.000000,83.138439
459,459,тв соединение отсутствует,20,103.923048,1,0,1.000000,83.138439
458,458,по ожидается восстановление,20,103.923048,1,0,1.000000,83.138439
456,456,legacy есть проблемы,20,103.923048,2,0,1.000000,83.138439
415,415,tdm зарегистрировано соединение,20,103.923048,2,0,0.465116,103.923048
416,416,отсутствует причина неверная,20,103.923048,1,0,0.003247,103.923048
420,420,цифровое тв соединение,20,103.923048,2,0,0.166667,103.923048
419,419,iot нет dhcp,20,103.923048,2,0,0.454545,103.923048
418,418,конфигурация по ожидается,20,103.923048,1,0,0.016849,103.923048
414,414,интернет gpon отсутствует,20,103.923048,2,0,0.266667,103.923048
417,417,беспроводной шпд не,20,103.923048,2,0,0.370370,103.923048
501,501,wi-fi есть,20,56.568542,1,1,0.434783,59.396970
502,502,xdsl нет,20,56.568542,1,0,0.243902,56.568542
496,496,wi-fi проблема,20,56.568542,1,1,0.434783,59.396970
497,497,legacy есть,20,56.568542,1,1,0.416667,59.396970
495,495,абонента передано,20,56.568542,0,1,0.000000,59.396970
498,498,pon соединение,20,56.568542,1,1,0.186916,59.396970
499,499,по ожидается,20,56.568542,0,1,0.000000,59.396970
500,500,тв соединение,20,56.568542,0,1,0.000000,59.396970
489,489,оборудования ожидается,21,59.396970,0,1,0.000000,62.366818
488,488,шпд неисправность,21,59.396970,1,1,0.061404,62.366818
398,398,качество причина неисправность,21,109.119201,1,0,0.010155,109.119201
446,446,оборудования ожидается восстановление,21,109.119201,1,0,1.000000,87.295361
445,445,шпд неисправность оборудования,21,109.119201,2,0,1.000000,87.295361
400,400,проблемы причина авария,21,109.119201,1,0,0.006028,109.119201
399,399,беспроводной шпд неисправность,21,109.119201,2,0,0.388889,109.119201
401,401,в интернет не,21,109.119201,1,0,0.015130,109.119201
443,443,xpon плохое качество,21,109.119201,2,0,1.000000,87.295361
444,444,все-в-одном соединение отсутствует,21,109.119201,2,0,1.000000,87.295361
487,487,все-в-одном соединение,21,59.396970,1,1,0.173554,62.366818
486,486,xpon плохое,21,59.396970,1,1,0.154412,62.366818
478,478,gpon не,22,62.225397,1,1,0.192982,65.336667
477,477,xpon неисправность,22,62.225397,1,1,0.161765,65.336667
492,492,pon проблема,22,62.225397,1,0,0.205607,62.225397
479,479,fttx соединение,22,62.225397,1,1,0.169231,65.336667
384,384,оборудования абонента выполняется,22,114.315353,1,0,0.015504,114.315353
385,385,wi-fi зарегистрировано не,22,114.315353,2,0,0.478261,114.315353
386,386,интернет xdsl есть,22,114.315353,2,0,0.158273,114.315353
387,387,интернет нет авторизации,22,114.315353,2,0,0.125714,114.315353
388,388,качество причина проблема,22,114.315353,1,0,0.010638,114.315353
438,438,шпд беспроводной шпд,22,114.315353,2,0,1.000000,91.452283
437,437,fttx соединение отсутствует,22,114.315353,2,0,1.000000,91.452283
480,480,шпд беспроводной,22,62.225397,1,1,0.064327,65.336667
490,490,iot gpon,22,62.225397,1,0,0.247191,62.225397
491,491,tdm авария,22,62.225397,1,0,0.511628,62.225397
435,435,xpon неисправность оборудования,22,114.315353,2,0,1.000000,91.452283
436,436,gpon не работают,22,114.315353,2,0,1.000000,91.452283

In [19]:
vectorizer = VocabularyVectorizer(
    "../data/vocabulary.csv"
)


X = vectorizer.transform(
    corpus
)


X.shape

(10000, 506)

In [20]:
joblib.dump(X, "../data/numpy_X_vectorized.joblib")

['../data/numpy_X_vectorized.joblib']

In [21]:
np.asarray(
    X.sum(axis=1)
).ravel().mean()

np.float64(8.6012)

In [22]:
nnz_per_doc = np.asarray(
    X.sum(axis=1)
).ravel()

pd.Series(nnz_per_doc).describe()

count    10000.000000
mean         8.601200
std          2.403734
min          3.000000
25%          7.000000
50%          8.000000
75%         10.000000
max         17.000000
dtype: float64

In [23]:
(df_vocab[
    df_vocab["text"].str.contains(
        "неисправность",
        na=False
    )
][
    [
        "token_id",
        "text",
        "freq"
    ]
])

     token_id                                   text  freq
0           0             неисправность оборудования  5343
4           4  неисправность оборудования провайдера  1479
7           7    неисправность оборудования абонента  1419
14         14                          неисправность  4890
74         74     причина неисправность оборудования   173
102       102                  причина неисправность   173
123       123      отсутствует причина неисправность    79
249       249        fttx неисправность оборудования    43
272       272         проблемы причина неисправность    32
339       339            интернет fttx неисправность    25
344       344                     fttx неисправность    43
356       356               витая пара неисправность    24
365       365        gpon неисправность оборудования    29
398       398         качество причина неисправность    21
399       399         беспроводной шпд неисправность    21
423       423        пара неисправность оборудования    24
430       430        xdsl неисправность оборудования    23
431       431         pon неисправность оборудования    23
435       435        xpon неисправность оборудования    22
445       445         шпд неисправность оборудования    21
451       451                     gpon неисправность    29
471       471                     пара неисправность    24
474       474                     xdsl неисправность    23
475       475                      pon неисправность    23
477       477                     xpon неисправность    22
488       488                      шпд неисправность    21